services:
  - type: web
    name: expenze-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: PGHOST
        sync: false
      - key: PGPORT
        value: 5432
      - key: PGDATABASE
        value: postgres
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
